name: deploy-prod

on:
  push:
    tags:
      - deploy-prod

jobs:
  deploy-app-beta:
    name: Deploy app to Fly.io prod
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          flyctl deploy --config fly-app-prod.toml --remote-only \
          -e "BOT_TOKEN=${{ secrets.BOT_TOKEN }},\
          DB_HOST=${{ secrets.DB_HOST }},\
          DB_NAME=${{ secrets.DB_NAME }},\
          DB_PASSWORD=${{ secrets.DB_PASSWORD }},\
          DB_PORT=${{ secrets.DB_PORT }},\
          DB_USER=${{ secrets.DB_USER }},\
          LOGGING_LEVEL=${{ secrets.LOGGING_LEVEL }},\
          TELEGRAM_BOT_MODE=${{ secrets.TELEGRAM_BOT_MODE }},\
          LINE_NOTIFY_REDIRECT_URL=${{ secrets.LINE_NOTIFY_REDIRECT_URL }},\
          LINE_NOTIFY_CLIENT_ID=${{ secrets.LINE_NOTIFY_CLIENT_ID }},\
          LINE_NOTIFY_CLIENT_SECRET=${{ secrets.LINE_NOTIFY_CLIENT_SECRET }},\
          PERIOD_HOUR=${{ secrets.PERIOD_HOUR }},\
          WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: echo "Deploy to fly prod"
